checks:
  duplicate:
    enabled: true
    exclude_patterns:
      - "test/"
      - "examples/"
  structure:
    enabled: true
    exclude_patterns:
      - "test/"

plugins:
  editorconfig:
    enabled: false
    config:
      editorconfig: .editorconfig
    exclude_patterns:
      - ".clangd/"
      - ".cache/"
  pep8:
    enabled: true
    exclude_patterns:
      - "test/test_fe_engine/py_engine/py_engine.py"
  cppcheck:
    enabled: true
    project: compile_commands.json
    language: c++
    check: warning, style, performance
    stds: [c++14]

  fixme:
    enabled: true
    exclude_patterns:
      - "doc/"

exclude_patterns:
- "third-party/"
- "build*/"
